# Generated by Django 5.0.6 on 2024-06-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0014_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
